/*
 * GraphLayoutPanel.java
 *
 * Created on November 24, 2008, 4:33 PM
 */

package studentbrowser;

import java.awt.Graphics;

/**
 *
 * @author  GuestUser
 */
public class GraphLayoutPanel extends javax.swing.JPanel 
{
    private StudentBrowserStudentStatisticsDialog parent;

    /** Creates new form GraphLayoutPanel */
    public GraphLayoutPanel(StudentBrowserStudentStatisticsDialog parent) 
    {
        this.parent = parent;
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics g) 
    {
        super.paintComponent(g);
        java.awt.Graphics2D g2D = (java.awt.Graphics2D)g;
        java.awt.Graphics2D imageG2D = parent.getGeneralGraphImageGraphics2D();
        Debug.line("Width,Height:"+getWidth()+","+getHeight());
        
        /* Baseline
        g2D.drawString("-4", 2, 423);
        */
        for(int i = 0; i < 4; i++)
        {
            g2D.drawString(Integer.toString(i-4),(2.0F+(i*48.480F)), 423.0F);
            imageG2D.drawString(Integer.toString(i-4),(2.0F+(i*48.480F)), 423.0F);
        }
        for(int i = 0; i < 5; i++)
        {
            g2D.drawString(Integer.toString(i),(200.0F+(i*48.400F)), 423.0F);
            imageG2D.drawString(Integer.toString(i),(200.0F+(i*48.400F)), 423.0F);
        }
        //g2D.draw(new java.awt.geom.Line2D.Double(0, 412, 419, 412));
        /*
        for(int i = 0; i < 4; i++)
            g2D.drawString(Integer.toString(i-4),(76.0F+(i*48.480F)), 423.0F);
        
        for(int i = 0; i < 5; i++)
            g2D.drawString(Integer.toString(i),(273.0F+(i*48.480F)), 423.0F);
        */
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
