/*
 * ImageFileViewPanel.java
 *
 * Created on November 24, 2008, 6:40 PM
 */

package studentbrowser;

import java.awt.Graphics;

/**
 *
 * @author  GuestUser
 */
public class ImageFileViewPanel extends javax.swing.JPanel {
    private java.awt.image.BufferedImage image;
    /** Creates new form ImageFileViewPanel */
    public ImageFileViewPanel(java.awt.image.BufferedImage image) 
    {
        initComponents();
        this.image = image;
    }

    @Override
    protected void paintComponent(Graphics g) 
    {
        super.paintComponent(g);
        java.awt.Graphics2D g2D = (java.awt.Graphics2D)g;
        
        //g2D.drawImage(image, 0, 0, getWidth(), getHeight(), null);
        g2D.drawImage(image, 0, 0, null);
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
